url: "http://deanattali.com"
timezone: "America/Vancouver"

title : Dean Attali
author :
  name : Dean Attali
  email : daattali@gmail.com
  github : daattali
  twitter : daattali

defaults:
  -
    scope:
      path: "" # all files
    values:
      layout: "default"