# Serving
url: "http://deanattali.com"  # full site URL
url-short: "deanattali.com" # how to display the url
baseurl: ""  # does not include hostname

# Header meta
name: Dean Attali
description: Dean Attali's website

# Outputting
timezone: "America/Vancouver"
markdown: redcarpet
highlighter: pygments
permalink: /:year-:month-:day-:title
paginate: 5

defaults:
  -
    scope:
      path: "" # all files
    values:
      layout: "default"

title : Dean Attali

# Change all these values or delete the ones you don't want.
# You should keep the "name" parameter since it will be used as the name of blog posts' author.
author:
  name: Dean Attali
  email: "daattali@gmail.com"
  facebook: daattali
  github: daattali
  twitter: daattali
  linkedin: "pub/dean-attali/8/946/143"
  stackoverflow: "users/3943160/daattali"
 
 # You can quickly enable/disable links from showing in the footer
footer-links-active:
  rss: false
  facebook: true
  email: true
  twitter: true
  github: true
  linkedin: false
  stackoverflow: false
 
avatar: "img/deanimg.jpeg"  # image to show in navbar
 
# List of links in the navbar
navbar-links:
  Home: ""
  About Me: "aboutme"
  Projects: "projects"
  Blog: "blog"
    
disqus: "deanattali-site"  # Your disqus shortname
google_analytics: "UA-59820529-1"  # Your Google Analytics ID

# Exclude these files from production site
exclude:
  - CNAME
  - LICENSE
  - README.md
