# Serving
url: "http://deanattali.com"  # full site URL
url-short: "deanattali.com" # how to display the url
baseurl: ""  # does not include hostname

# Header meta
name: Dean Attali
description: Dean Attali's website

# Outputting
timezone: "America/Vancouver"
markdown: redcarpet
highlighter: pygments
permalink: /:year-:month-:day-:title
paginate: 5

defaults:
  -
    scope:
      path: "" # all files
    values:
      layout: "default"

title : Dean Attali

avatar: "https://avatars0.githubusercontent.com/u/952340?v=3&s=140"

author:
  name: Dean Attali
  email: "daattali@gmail.com"
  facebook: daattali
  github: daattali
  twitter: daattali
  linkedin: "pub/dean-attali/8/946/143"
  stackoverflow: "users/3943160/daattali"

footer-links-active:
  rss: true
  facebook: true
  email: true
  github: true
  stackoverflow: true
    
disqus: "deanattali-site"
google_analytics: "UA-59820529-1"

# The release of Jekyll Now
version: "v1.0.0"

# Exclude these files from production site
exclude:
  - CNAME
  - LICENSE
  - README.md
